In [66]:
import numpy as np

In [67]:
### for two dimensionalarray


In [68]:
arr2d_1 =np.array([[1,2,3,4,],
                 [5,6,7,8],
                 [9,10,11,12]])
arr2d_2 =np.array([[14,15,16,2],
                 [17,18,19,4],
                 [20,21,22,7]])
                 

In [69]:
np.concatenate((arr2d_1,arr2d_2), axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [14, 15, 16,  2],
       [17, 18, 19,  4],
       [20, 21, 22,  7]])

### hstack and vstack

In [70]:
arr_1= np.array([[1,8,10,11],
                 [12,13,14,15]])
arr_2 = np.array([[2,2,3,4]])

In [71]:
np.vstack((arr_1,arr_2))

array([[ 1,  8, 10, 11],
       [12, 13, 14, 15],
       [ 2,  2,  3,  4]])

In [72]:
arr_3= np.array([[23],
                 [34]])

In [73]:
arr4=np.hstack((arr_1,arr_3))
print(arr4)

[[ 1  8 10 11 23]
 [12 13 14 15 34]]


### slicing

In [74]:
array1 = np.arange(1,11)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
array2= array1[3:7]
array2

array([4, 5, 6, 7])

In [76]:
array2 =np.array([[4,5,6,7,],
                  [1,2,3,4],
                  [2,4,1,5]])
array2.shape

(3, 4)

In [77]:
array2.ndim

2

In [78]:
print(array2[1,2])

3


In [79]:
print(array2[2,0])

2


In [80]:
print(array2[0: , 1:3])

[[5 6]
 [2 3]
 [4 1]]


In [81]:
array2.shape

(3, 4)

In [82]:
array2.reshape(4,3 )

array([[4, 5, 6],
       [7, 1, 2],
       [3, 4, 2],
       [4, 1, 5]])

In [83]:
array2.reshape(12)

array([4, 5, 6, 7, 1, 2, 3, 4, 2, 4, 1, 5])

In [84]:
array2.reshape(3,2,2)

array([[[4, 5],
        [6, 7]],

       [[1, 2],
        [3, 4]],

       [[2, 4],
        [1, 5]]])

In [85]:
array5= np.arange(1,101)
array5.reshape(5,20)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
         34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
         54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
         74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
         94,  95,  96,  97,  98,  99, 100]])

### random array in numpy

In [86]:
# rand() - gives the random value between 0 and 1
# randint() - give the random integer value with in the speciied range 

In [87]:
array_1 = np.random.rand(4,6)

In [88]:
array_1

array([[0.64189181, 0.17777004, 0.92640388, 0.86771535, 0.08662202,
        0.31382255],
       [0.5439659 , 0.88875924, 0.11002354, 0.05001222, 0.20764552,
        0.55330909],
       [0.77025136, 0.52997237, 0.75828309, 0.90739549, 0.03827147,
        0.28231067],
       [0.05508797, 0.04907507, 0.32993115, 0.45890771, 0.36741005,
        0.890113  ]])

In [89]:
array_2 = np.random.rand(10)

In [90]:
array_2

array([0.74864848, 0.39030133, 0.77370349, 0.88767503, 0.19549016,
       0.35699454, 0.10476365, 0.00744448, 0.71124654, 0.57646536])

### randint method

In [101]:
array_3 = np.random.randint(10,15, size=(7))

In [92]:
array_3

array([10, 11, 13, 14, 13, 10, 11], dtype=int32)

### spliting in numpy array

In [96]:
array1= np.random.randint(100,500, size=(9,6))

In [94]:
array1

array([[233, 358, 250, 365, 414, 311],
       [484, 368, 202, 149, 206, 332],
       [146, 376, 276, 200, 247, 258],
       [310, 247, 382, 361, 374, 225],
       [452, 317, 193, 178, 330, 135],
       [450, 158, 449, 331, 160, 255],
       [151, 257, 257, 159, 116, 116],
       [379, 109, 472, 207, 128, 291],
       [456, 139, 427, 110, 191, 446]], dtype=int32)

In [99]:
array1_1 , array1_2 ,array1_3 = np.split(array1,3,axis=0)

In [ ]:
array1_1

array([[107, 437, 258, 166, 416, 256],
       [363, 422, 463, 466, 373, 109],
       [176, 372, 159, 379, 314, 288],
       [310, 361, 433, 442, 162, 413],
       [332, 380, 447, 492, 424, 280]], dtype=int32)

In [ ]:
array1_2

array([[346, 152, 165, 174, 441, 255],
       [405, 449, 229, 203, 253, 313],
       [373, 413, 178, 240, 409, 230],
       [211, 233, 134, 334, 417, 364],
       [376, 309, 431, 448, 216, 403]], dtype=int32)

In [100]:
array1_3

array([[392, 207, 351, 470, 265, 343],
       [243, 299, 423, 376, 233, 241],
       [108, 203, 299, 219, 121, 411]], dtype=int32)

### columnwise split

In [102]:
array1= np.random.randint(100,500, size=(10,6))

In [103]:
array1

array([[127, 470, 194, 403, 428, 303],
       [369, 110, 252, 411, 106, 379],
       [154, 481, 318, 406, 168, 411],
       [316, 112, 173, 246, 406, 120],
       [374, 128, 136, 291, 165, 159],
       [217, 108, 156, 265, 451, 172],
       [484, 172, 278, 302, 100, 299],
       [312, 353, 162, 217, 453, 412],
       [356, 257, 160, 275, 370, 171],
       [198, 399, 288, 462, 125, 328]], dtype=int32)

In [105]:
array1_1,array1_2 = np.split(array1,2 , axis=1)

In [106]:
array1_1

array([[127, 470, 194],
       [369, 110, 252],
       [154, 481, 318],
       [316, 112, 173],
       [374, 128, 136],
       [217, 108, 156],
       [484, 172, 278],
       [312, 353, 162],
       [356, 257, 160],
       [198, 399, 288]], dtype=int32)

In [107]:
array1_2

array([[403, 428, 303],
       [411, 106, 379],
       [406, 168, 411],
       [246, 406, 120],
       [291, 165, 159],
       [265, 451, 172],
       [302, 100, 299],
       [217, 453, 412],
       [275, 370, 171],
       [462, 125, 328]], dtype=int32)

In [108]:
array1

array([[127, 470, 194, 403, 428, 303],
       [369, 110, 252, 411, 106, 379],
       [154, 481, 318, 406, 168, 411],
       [316, 112, 173, 246, 406, 120],
       [374, 128, 136, 291, 165, 159],
       [217, 108, 156, 265, 451, 172],
       [484, 172, 278, 302, 100, 299],
       [312, 353, 162, 217, 453, 412],
       [356, 257, 160, 275, 370, 171],
       [198, 399, 288, 462, 125, 328]], dtype=int32)

In [109]:
array1_1,array1_2 = np.split(array1,[5],axis=1)

In [110]:
array1_1

array([[127, 470, 194, 403, 428],
       [369, 110, 252, 411, 106],
       [154, 481, 318, 406, 168],
       [316, 112, 173, 246, 406],
       [374, 128, 136, 291, 165],
       [217, 108, 156, 265, 451],
       [484, 172, 278, 302, 100],
       [312, 353, 162, 217, 453],
       [356, 257, 160, 275, 370],
       [198, 399, 288, 462, 125]], dtype=int32)

In [111]:
array1_2

array([[303],
       [379],
       [411],
       [120],
       [159],
       [172],
       [299],
       [412],
       [171],
       [328]], dtype=int32)

In [112]:
array1

array([[127, 470, 194, 403, 428, 303],
       [369, 110, 252, 411, 106, 379],
       [154, 481, 318, 406, 168, 411],
       [316, 112, 173, 246, 406, 120],
       [374, 128, 136, 291, 165, 159],
       [217, 108, 156, 265, 451, 172],
       [484, 172, 278, 302, 100, 299],
       [312, 353, 162, 217, 453, 412],
       [356, 257, 160, 275, 370, 171],
       [198, 399, 288, 462, 125, 328]], dtype=int32)

In [113]:
array1_1,array1_2,array1_3 = np.split(array1,[3,5],axis=1)

In [114]:
array1_1

array([[127, 470, 194],
       [369, 110, 252],
       [154, 481, 318],
       [316, 112, 173],
       [374, 128, 136],
       [217, 108, 156],
       [484, 172, 278],
       [312, 353, 162],
       [356, 257, 160],
       [198, 399, 288]], dtype=int32)

In [115]:
array1_2

array([[403, 428],
       [411, 106],
       [406, 168],
       [246, 406],
       [291, 165],
       [265, 451],
       [302, 100],
       [217, 453],
       [275, 370],
       [462, 125]], dtype=int32)

In [117]:
array1_3

array([[303],
       [379],
       [411],
       [120],
       [159],
       [172],
       [299],
       [412],
       [171],
       [328]], dtype=int32)

In [118]:
array1_1,array1_2,array1_3 = np.split(array1,[3,5],axis=0)

In [119]:
array1_1

array([[127, 470, 194, 403, 428, 303],
       [369, 110, 252, 411, 106, 379],
       [154, 481, 318, 406, 168, 411]], dtype=int32)

In [120]:
array1_2

array([[316, 112, 173, 246, 406, 120],
       [374, 128, 136, 291, 165, 159]], dtype=int32)

In [121]:
array1_3

array([[217, 108, 156, 265, 451, 172],
       [484, 172, 278, 302, 100, 299],
       [312, 353, 162, 217, 453, 412],
       [356, 257, 160, 275, 370, 171],
       [198, 399, 288, 462, 125, 328]], dtype=int32)

### load the dataset into numpy array

In [152]:
iris_array = np.genfromtxt(r"C:\Users\David\Desktop\machine larning\numpy_learning\iris.txt", delimiter=',')

In [156]:
iris_array

array([[5.1, 3.5, 1.4, 0.2, nan],
       [4.9, 3. , 1.4, 0.2, nan],
       [4.7, 3.2, 1.3, 0.2, nan],
       [4.6, 3.1, 1.5, 0.2, nan],
       [5. , 3.6, 1.4, 0.2, nan],
       [5.4, 3.9, 1.7, 0.4, nan],
       [4.6, 3.4, 1.4, 0.3, nan],
       [5. , 3.4, 1.5, 0.2, nan],
       [4.4, 2.9, 1.4, 0.2, nan],
       [4.9, 3.1, 1.5, 0.1, nan],
       [5.4, 3.7, 1.5, 0.2, nan],
       [4.8, 3.4, 1.6, 0.2, nan],
       [4.8, 3. , 1.4, 0.1, nan],
       [4.3, 3. , 1.1, 0.1, nan],
       [5.8, 4. , 1.2, 0.2, nan],
       [5.7, 4.4, 1.5, 0.4, nan],
       [5.4, 3.9, 1.3, 0.4, nan],
       [5.1, 3.5, 1.4, 0.3, nan],
       [5.7, 3.8, 1.7, 0.3, nan],
       [5.1, 3.8, 1.5, 0.3, nan],
       [5.4, 3.4, 1.7, 0.2, nan],
       [5.1, 3.7, 1.5, 0.4, nan],
       [4.6, 3.6, 1. , 0.2, nan],
       [5.1, 3.3, 1.7, 0.5, nan],
       [4.8, 3.4, 1.9, 0.2, nan],
       [5. , 3. , 1.6, 0.2, nan],
       [5. , 3.4, 1.6, 0.4, nan],
       [5.2, 3.5, 1.5, 0.2, nan],
       [5.2, 3.4, 1.4, 0.2, nan],
       [4.7, 3

In [137]:
iris_array_1,iris_array_2 = np.split(iris_array,[4],axis=1)

In [138]:
iris_array_1

array([['5.1', '3.5', '1.4', '0.2'],
       ['4.9', '3.0', '1.4', '0.2'],
       ['4.7', '3.2', '1.3', '0.2'],
       ['4.6', '3.1', '1.5', '0.2'],
       ['5.0', '3.6', '1.4', '0.2'],
       ['5.4', '3.9', '1.7', '0.4'],
       ['4.6', '3.4', '1.4', '0.3'],
       ['5.0', '3.4', '1.5', '0.2'],
       ['4.4', '2.9', '1.4', '0.2'],
       ['4.9', '3.1', '1.5', '0.1'],
       ['5.4', '3.7', '1.5', '0.2'],
       ['4.8', '3.4', '1.6', '0.2'],
       ['4.8', '3.0', '1.4', '0.1'],
       ['4.3', '3.0', '1.1', '0.1'],
       ['5.8', '4.0', '1.2', '0.2'],
       ['5.7', '4.4', '1.5', '0.4'],
       ['5.4', '3.9', '1.3', '0.4'],
       ['5.1', '3.5', '1.4', '0.3'],
       ['5.7', '3.8', '1.7', '0.3'],
       ['5.1', '3.8', '1.5', '0.3'],
       ['5.4', '3.4', '1.7', '0.2'],
       ['5.1', '3.7', '1.5', '0.4'],
       ['4.6', '3.6', '1.0', '0.2'],
       ['5.1', '3.3', '1.7', '0.5'],
       ['4.8', '3.4', '1.9', '0.2'],
       ['5.0', '3.0', '1.6', '0.2'],
       ['5.0', '3.4', '1.6', '0.4'],
 

In [139]:
iris_array_2

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-se

In [140]:
array1 = np.array([12,14,16,13,10])
mean= np.mean(array1)

In [141]:
mean

np.float64(13.0)

In [144]:
median = np.median(array1)
median

np.float64(13.0)

In [145]:
standard_deviation = np.std(array1)

In [146]:
standard_deviation

np.float64(2.0)

In [147]:
array_2 = np.random.randint(15,25, size=(6,4))

In [148]:
array_2


array([[15, 20, 18, 22],
       [22, 19, 21, 24],
       [19, 22, 21, 18],
       [19, 22, 18, 18],
       [21, 15, 18, 17],
       [23, 21, 17, 22]], dtype=int32)

In [149]:
array_2_mean = np.mean(array_2,axis=0)

In [150]:
array_2_mean

array([19.83333333, 19.83333333, 18.83333333, 20.16666667])

In [155]:
iris_array_2 =np.mean(iris_array,axis=0)
print(iris_array_2)

[5.84333333 3.054      3.75866667 1.19866667        nan]
